package com.linkstec.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class MotActivity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private BigDecimal activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.ACTIVITY_NAME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private String activityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.ACTIVITY_DESC
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private String activityDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.ACTIVITY_COST
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private BigDecimal activityCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.START_DATE
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.EXPIRED_DATE
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private Date expiredDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.CREATOR
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private BigDecimal creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.MODIFY_TIME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.STATUS
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private BigDecimal status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.EVENT_LIST
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private String eventList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MOT_ACTIVITY.ACTIVITY_FLOW
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    private String activityFlow;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.ACTIVITY_ID
     *
     * @return the value of MOT_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public BigDecimal getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.ACTIVITY_ID
     *
     * @param activityId the value for MOT_ACTIVITY.ACTIVITY_ID
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setActivityId(BigDecimal activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.ACTIVITY_NAME
     *
     * @return the value of MOT_ACTIVITY.ACTIVITY_NAME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.ACTIVITY_NAME
     *
     * @param activityName the value for MOT_ACTIVITY.ACTIVITY_NAME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.ACTIVITY_DESC
     *
     * @return the value of MOT_ACTIVITY.ACTIVITY_DESC
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public String getActivityDesc() {
        return activityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.ACTIVITY_DESC
     *
     * @param activityDesc the value for MOT_ACTIVITY.ACTIVITY_DESC
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setActivityDesc(String activityDesc) {
        this.activityDesc = activityDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.ACTIVITY_COST
     *
     * @return the value of MOT_ACTIVITY.ACTIVITY_COST
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public BigDecimal getActivityCost() {
        return activityCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.ACTIVITY_COST
     *
     * @param activityCost the value for MOT_ACTIVITY.ACTIVITY_COST
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setActivityCost(BigDecimal activityCost) {
        this.activityCost = activityCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.START_DATE
     *
     * @return the value of MOT_ACTIVITY.START_DATE
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.START_DATE
     *
     * @param startDate the value for MOT_ACTIVITY.START_DATE
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.EXPIRED_DATE
     *
     * @return the value of MOT_ACTIVITY.EXPIRED_DATE
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public Date getExpiredDate() {
        return expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.EXPIRED_DATE
     *
     * @param expiredDate the value for MOT_ACTIVITY.EXPIRED_DATE
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setExpiredDate(Date expiredDate) {
        this.expiredDate = expiredDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.CREATOR
     *
     * @return the value of MOT_ACTIVITY.CREATOR
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public BigDecimal getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.CREATOR
     *
     * @param creator the value for MOT_ACTIVITY.CREATOR
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setCreator(BigDecimal creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.CREATE_TIME
     *
     * @return the value of MOT_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.CREATE_TIME
     *
     * @param createTime the value for MOT_ACTIVITY.CREATE_TIME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.MODIFY_TIME
     *
     * @return the value of MOT_ACTIVITY.MODIFY_TIME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.MODIFY_TIME
     *
     * @param modifyTime the value for MOT_ACTIVITY.MODIFY_TIME
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.STATUS
     *
     * @return the value of MOT_ACTIVITY.STATUS
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public BigDecimal getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.STATUS
     *
     * @param status the value for MOT_ACTIVITY.STATUS
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setStatus(BigDecimal status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.EVENT_LIST
     *
     * @return the value of MOT_ACTIVITY.EVENT_LIST
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public String getEventList() {
        return eventList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.EVENT_LIST
     *
     * @param eventList the value for MOT_ACTIVITY.EVENT_LIST
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setEventList(String eventList) {
        this.eventList = eventList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MOT_ACTIVITY.ACTIVITY_FLOW
     *
     * @return the value of MOT_ACTIVITY.ACTIVITY_FLOW
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public String getActivityFlow() {
        return activityFlow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MOT_ACTIVITY.ACTIVITY_FLOW
     *
     * @param activityFlow the value for MOT_ACTIVITY.ACTIVITY_FLOW
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    public void setActivityFlow(String activityFlow) {
        this.activityFlow = activityFlow;
    }
}