package com.linkstec.mybatis.mapper;

import com.linkstec.mybatis.model.MotActivity;
import com.linkstec.mybatis.model.MotActivityExample;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface MotActivityMapper {
	
	
	
	public List<MotActivity> getByPage(Map<String, Object> requestMap);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int countByExample(MotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int deleteByExample(MotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int insert(MotActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int insertSelective(MotActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    List<MotActivity> selectByExampleWithBLOBs(MotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    List<MotActivity> selectByExample(MotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    MotActivity selectByPrimaryKey(BigDecimal activityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") MotActivity record, @Param("example") MotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") MotActivity record, @Param("example") MotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int updateByExample(@Param("record") MotActivity record, @Param("example") MotActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int updateByPrimaryKeySelective(MotActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(MotActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOT_ACTIVITY
     *
     * @mbggenerated Wed Apr 19 15:09:45 CST 2017
     */
    int updateByPrimaryKey(MotActivity record);
}